language: objective-c
osx_image: xcode7.3
before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
  - export PATH=$HOME/.cargo/bin:$PATH
install:
  - cargo install
script:
  - cargo build --release
cache:
  directories:
    - $HOME/.cargo
